"""
Composites the generated AI visual cutaway images onto the render,
positioning each per its stored display_mode (OVERLAY_CARD,
FULL_FRAME_CONTAIN, FULL_FRAME_COVER) and position_x/position_y fraction
(as dragged in the GUI's placement-editor preview, gui_app/mixins/
ai_visual_preview.py, or left at its planned default). Reads
output/ai_visual_plan.json (written by ai_visual_planner.py, images
generated by generate_ai_visual_assets.py) plus the combined edit plan to
remap clip timing through any applied cuts.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    from .editor_asset_plan import (
        clips_of_kind,
        editor_plan_context_matches,
        load_editor_asset_plan,
    )
except ImportError:
    from editor_asset_plan import (
        clips_of_kind,
        editor_plan_context_matches,
        load_editor_asset_plan,
    )

try:
    from .visual_emphasis import (
        content_rect_from_settings,
        load_render_settings,
    )
except ImportError:
    from visual_emphasis import (
        content_rect_from_settings,
        load_render_settings,
    )

try:
    from .canvas_config import OUTPUT_HEIGHT as FRAME_HEIGHT, OUTPUT_WIDTH as FRAME_WIDTH
except ImportError:
    from canvas_config import OUTPUT_HEIGHT as FRAME_HEIGHT, OUTPUT_WIDTH as FRAME_WIDTH

try:
    from .pipeline_paths import (
        AI_VISUAL_MAPPED_PLAN_PATH as MAPPED_PLAN_PATH,
        AI_VISUAL_PLAN_PATH as PLAN_PATH,
        COMBINED_EDIT_PLAN_PATH as COMBINED_PLAN_PATH,
        TEMPORAL_EDIT_PLAN_PATH as TEMPORAL_PLAN_PATH,
    )
except ImportError:
    from pipeline_paths import (
        AI_VISUAL_MAPPED_PLAN_PATH as MAPPED_PLAN_PATH,
        AI_VISUAL_PLAN_PATH as PLAN_PATH,
        COMBINED_EDIT_PLAN_PATH as COMBINED_PLAN_PATH,
        TEMPORAL_EDIT_PLAN_PATH as TEMPORAL_PLAN_PATH,
    )


ROOT = Path(__file__).resolve().parent.parent

VIDEO_PATH = (
    ROOT
    / "output"
    / "rendered"
    / "short1_tight.mp4"
)

MANIFEST_PATH = (
    ROOT
    / "output"
    / "ai_visual_assets"
    / "manifest.json"
)

TEMP_PATH = (
    ROOT
    / "output"
    / "rendered"
    / "short1_visuals_tmp.mp4"
)

CARD_MAX_WIDTH = 842
CARD_MAX_HEIGHT = 882
CARD_BORDER = 12
CARD_Y_FACTOR = 0.22
CARD_DIM_ALPHA = 0.0
CONTAIN_DIM_ALPHA = 0.0


def load_json(
    path: Path,
) -> dict[str, Any]:

    try:
        data = json.loads(
            path.read_text(
                encoding="utf-8"
            )
        )
    except (
        OSError,
        json.JSONDecodeError,
    ):
        return {}

    return data if isinstance(
        data,
        dict,
    ) else {}


def keep_segments(
    plan: dict[str, Any],
    duration: float,
) -> list[
    tuple[float, float]
]:

    raw = plan.get(
        "keep_segments",
        [],
    )

    result: list[
        tuple[float, float]
    ] = []

    if isinstance(
        raw,
        list,
    ):

        for item in raw:

            if not isinstance(
                item,
                dict,
            ):
                continue

            try:
                start = float(
                    item.get(
                        "start",
                        0.0,
                    )
                )
                end = float(
                    item.get(
                        "end",
                        start,
                    )
                )
            except (
                TypeError,
                ValueError,
            ):
                continue

            if end > start:
                result.append(
                    (
                        start,
                        end,
                    )
                )

    if result:
        return result

    return [
        (
            0.0,
            duration,
        )
    ]


def map_source_interval_to_tight(
    source_start: float,
    source_end: float,
    selection_start: float,
    keeps: list[
        tuple[float, float]
    ],
) -> tuple[
    float,
    float,
] | None:

    base_start = max(
        0.0,
        source_start
        - selection_start,
    )

    base_end = max(
        base_start,
        source_end
        - selection_start,
    )

    accumulated = 0.0
    pieces: list[
        tuple[float, float]
    ] = []

    for keep_start, keep_end in keeps:

        overlap_start = max(
            base_start,
            keep_start,
        )

        overlap_end = min(
            base_end,
            keep_end,
        )

        if overlap_end > overlap_start:

            pieces.append(
                (
                    accumulated
                    + overlap_start
                    - keep_start,
                    accumulated
                    + overlap_end
                    - keep_start,
                )
            )

        accumulated += (
            keep_end
            - keep_start
        )

    if not pieces:
        return None

    return (
        pieces[0][0],
        pieces[-1][1],
    )


def map_tight_time_to_final(
    tight_time: float,
    temporal_plan: dict[str, Any],
) -> float:

    if not temporal_plan.get(
        "applied",
        False,
    ):
        return tight_time

    mapping = temporal_plan.get(
        "time_mapping",
        [],
    )

    if not isinstance(
        mapping,
        list,
    ):
        return tight_time

    final_duration = float(
        temporal_plan.get(
            "estimated_final_duration_seconds",
            tight_time,
        )
        or tight_time
    )

    previous_output = 0.0

    for segment in mapping:

        if not isinstance(
            segment,
            dict,
        ):
            continue

        if segment.get(
            "kind"
        ) != "source":
            continue

        source_start = float(
            segment.get(
                "source_start",
                0.0,
            )
            or 0.0
        )
        source_end = float(
            segment.get(
                "source_end",
                source_start,
            )
            or source_start
        )
        output_start = float(
            segment.get(
                "output_start",
                previous_output,
            )
            or previous_output
        )
        output_end = float(
            segment.get(
                "output_end",
                output_start,
            )
            or output_start
        )
        speed = float(
            segment.get(
                "speed",
                1.0,
            )
            or 1.0
        )

        if source_start <= tight_time <= source_end:
            return max(
                0.0,
                min(
                    final_duration,
                    output_start
                    + (
                        tight_time
                        - source_start
                    )
                    / max(
                        0.001,
                        speed,
                    ),
                ),
            )

        previous_output = output_end

    return max(
        0.0,
        min(
            final_duration,
            previous_output,
        ),
    )


def map_tight_interval_to_final(
    tight_start: float,
    tight_end: float,
    temporal_plan: dict[str, Any],
) -> tuple[float, float]:

    final_start = map_tight_time_to_final(
        tight_start,
        temporal_plan,
    )
    final_end = map_tight_time_to_final(
        tight_end,
        temporal_plan,
    )

    return (
        final_start,
        max(
            final_start,
            final_end,
        ),
    )


def probe_duration(
    video_path: Path,
) -> float:

    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(
                video_path
            ),
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )

    return float(
        result.stdout.strip()
    )


def normalize_display_mode(
    value: str,
) -> str:

    normalized = str(
        value
        or ""
    ).strip().upper()
    if normalized in {
        "OVERLAY_CARD",
        "FULL_FRAME_CONTAIN",
        "FULL_FRAME_COVER",
    }:
        return normalized
    return "OVERLAY_CARD"


def coerce_scale(
    value: Any,
) -> float:

    try:
        number = float(
            value
        )
    except (
        TypeError,
        ValueError,
    ):
        number = 1.0

    return max(
        0.6,
        min(
            1.4,
            number,
        ),
    )


def coerce_position(
    value: Any,
) -> float:

    try:
        number = float(
            value
        )
    except (
        TypeError,
        ValueError,
    ):
        number = 0.0

    return max(
        -1.0,
        min(
            1.0,
            number,
        ),
    )


def scale_opacity(
    mode: str,
) -> float:

    if mode == "OVERLAY_CARD":
        return 0.985
    return 1.0


def build_filter(
    mapped_assets: list[
        dict[str, Any]
    ],
    content_rect: tuple[int, int, int, int] = (
        0,
        0,
        FRAME_WIDTH,
        FRAME_HEIGHT,
    ),
) -> str:

    (
        content_x,
        content_y,
        content_width,
        content_height,
    ) = content_rect

    chains = [
        "[0:v]setpts=PTS-STARTPTS[base0]"
    ]

    previous = "base0"

    for index, asset in enumerate(
        mapped_assets,
        start=1,
    ):

        start = float(
            asset["tight_start"]
        )

        end = float(
            asset["tight_end"]
        )
        mode = normalize_display_mode(
            asset.get(
                "display_mode",
                "OVERLAY_CARD",
            )
        )
        scale = coerce_scale(
            asset.get(
                "scale",
                1.0,
            )
        )
        position_x = coerce_position(
            asset.get(
                "position_x",
                0.0,
            )
        )
        position_y = coerce_position(
            asset.get(
                "position_y",
                0.0,
            )
        )
        dim_alpha = 0.0

        if mode == "FULL_FRAME_COVER":
            cover_scale = max(
                1.0,
                scale,
            )
            cover_width = max(
                FRAME_WIDTH,
                int(
                    round(
                        FRAME_WIDTH
                        * cover_scale
                    )
                ),
            )
            cover_height = max(
                FRAME_HEIGHT,
                int(
                    round(
                        FRAME_HEIGHT
                        * cover_scale
                    )
                ),
            )
            crop_x_factor = (
                1.0
                - position_x
            ) / 2.0
            crop_y_factor = (
                1.0
                - position_y
            ) / 2.0
            chains.append(
                (
                    f"[{index}:v]"
                    f"scale={cover_width}:{cover_height}:"
                    "force_original_aspect_ratio=increase,"
                    f"crop={FRAME_WIDTH}:{FRAME_HEIGHT}:"
                    f"x='(iw-ow)*{crop_x_factor:.6f}':"
                    f"y='(ih-oh)*{crop_y_factor:.6f}',"
                    "setsar=1"
                    f"[vis{index}]"
                )
            )
        elif mode == "FULL_FRAME_CONTAIN":
            contain_width = max(
                320,
                int(
                    round(
                        FRAME_WIDTH
                        * scale
                    )
                ),
            )
            contain_height = max(
                320,
                int(
                    round(
                        FRAME_HEIGHT
                        * scale
                    )
                ),
            )
            chains.append(
                (
                    f"[{index}:v]"
                    f"scale={contain_width}:{contain_height}:"
                    "force_original_aspect_ratio=decrease,"
                    "setsar=1,"
                    "format=rgba,"
                    f"colorchannelmixer=aa={scale_opacity(mode):.3f}"
                    f"[vis{index}]"
                )
            )
            dim_alpha = CONTAIN_DIM_ALPHA
        else:
            overlay_width = min(
                FRAME_WIDTH,
                max(
                    280,
                    int(
                        round(
                            CARD_MAX_WIDTH
                            * scale
                        )
                    ),
                ),
            )
            overlay_height = min(
                FRAME_HEIGHT,
                max(
                    280,
                    int(
                        round(
                            CARD_MAX_HEIGHT
                            * scale
                        )
                    ),
                ),
            )
            chains.append(
                (
                    f"[{index}:v]"
                    f"scale={overlay_width}:{overlay_height}:"
                    "force_original_aspect_ratio=increase,"
                    f"crop={overlay_width}:{overlay_height},"
                    "setsar=1,"
                    "format=rgba,"
                    f"colorchannelmixer=aa={scale_opacity(mode):.3f}"
                    f"[vis{index}]"
                )
            )
            dim_alpha = CARD_DIM_ALPHA

        pre_overlay = previous
        if dim_alpha > 0.0:
            dim_label = f"dim{index}"
            chains.append(
                (
                    f"[{previous}]"
                    "drawbox="
                    "x=0:y=0:w=iw:h=ih:"
                    f"color=black@{dim_alpha:.3f}:"
                    "t=fill:"
                    f"enable='between(t,{start:.3f},{end:.3f})'"
                    f"[{dim_label}]"
                )
            )
            pre_overlay = dim_label

        output_label = (
            f"base{index}"
        )

        if mode == "FULL_FRAME_COVER":
            # Deliberately covers the entire canvas edge-to-edge,
            # including behind where letterbox bars would be -- not
            # content-rect-relative by design.
            x_expr = "0"
            y_expr = "0"
        elif mode == "FULL_FRAME_CONTAIN":
            # Center within the actual visible content area, not the
            # full (possibly letterboxed) canvas.
            x_expr = (
                f"{content_x}+({content_width}-w)/2"
                f"+({position_x:.6f})*abs({content_width}-w)/2"
            )
            y_expr = (
                f"{content_y}+({content_height}-h)/2"
                f"+({position_y:.6f})*abs({content_height}-h)/2"
            )
        else:
            x_expr = (
                f"{content_x}+({content_width}-w)"
                f"*(0.5+0.5*({position_x:.6f}))"
            )
            # Local (content-relative) rest position, then offset by the
            # content rect's own top -- content_y is 0 when there's no
            # letterboxing, so this is unchanged in that case.
            local_base_y = (
                f"max(110,({content_height}-h)*{CARD_Y_FACTOR:.3f})"
            )
            base_y = (
                f"({content_y}+({local_base_y}))"
            )
            if position_y >= 0.0:
                y_expr = (
                    f"({base_y})"
                    f"+({position_y:.6f})"
                    f"*(({content_y}+{content_height}-h)-({base_y}))"
                )
            else:
                y_expr = (
                    f"({base_y})"
                    f"+({position_y:.6f})"
                    f"*(({base_y})-{content_y})"
                )

        chains.append(
            (
                f"[{pre_overlay}]"
                f"[vis{index}]"
                "overlay="
                f"x='{x_expr}':"
                f"y='{y_expr}':"
                f"enable='between(t,{start:.3f},{end:.3f})'"
                f"[{output_label}]"
            )
        )

        previous = output_label

    chains.append(
        f"[{previous}]format=yuv420p[outv]"
    )

    return ";".join(
        chains
    )


def compute_keeps(
    combined_plan: dict[str, Any],
) -> list[Any]:
    """
    Resolve the kept-segment timeline (source-video seconds) that source
    intervals get mapped through, using the combined edit plan's recorded
    original duration when present and probing the tight video otherwise.
    """
    try:
        original_duration = float(
            combined_plan.get(
                "original_duration_seconds",
                probe_duration(
                    VIDEO_PATH
                ),
            )
        )
    except (
        TypeError,
        ValueError,
    ):
        original_duration = probe_duration(
            VIDEO_PATH
        )

    return keep_segments(
        combined_plan,
        original_duration,
    )


def build_asset_maps(
    assets: list[Any],
) -> tuple[
    dict[int, dict[str, Any]],
    dict[str, dict[str, Any]],
]:
    """
    Index the generated-asset manifest both by slot_index and by slot_id,
    so a visual slot can be matched to its generated asset either way.
    """
    asset_map_by_index = {
        int(
            item.get(
                "slot_index",
                0,
            )
        ): item
        for item in assets
        if isinstance(
            item,
            dict,
        )
    }

    asset_map_by_id = {
        str(
            item.get(
                "slot_id",
                "",
            )
            or ""
        ): item
        for item in assets
        if isinstance(
            item,
            dict,
        )
        and item.get(
            "slot_id"
        )
    }

    return asset_map_by_index, asset_map_by_id


def load_render_context() -> tuple[
    list[dict[str, Any]],
    dict[str, Any],
    float,
    float,
]:
    """
    Load render settings and, when the editor's asset plan still matches
    the current source video/selection, the active AI_VISUAL clips it
    defines. Returns (editor_visual_clips, render_settings,
    selection_start, selection_end); editor_visual_clips is empty when
    there is no editor asset plan or it no longer matches the current
    selection, in which case the caller falls back to the raw visual
    plan's slots instead.
    """
    editor_asset_plan = load_editor_asset_plan()
    render_settings = load_render_settings()
    source_video = str(
        render_settings.get(
            "source_video",
            "",
        )
        or ""
    )
    try:
        selection_start = float(
            render_settings.get(
                "selection_start",
                -1.0,
            )
        )
        selection_end = float(
            render_settings.get(
                "selection_end",
                -1.0,
            )
        )
    except (TypeError, ValueError):
        selection_start = -1.0
        selection_end = -1.0

    if editor_plan_context_matches(
        editor_asset_plan,
        source_video,
        selection_start,
        selection_end,
    ):
        editor_visual_clips = clips_of_kind(
            editor_asset_plan,
            "AI_VISUAL",
            active_only=True,
        )
    else:
        editor_visual_clips = []

    return (
        editor_visual_clips,
        render_settings,
        selection_start,
        selection_end,
    )


def build_visual_items(
    editor_visual_clips: list[dict[str, Any]],
    slots: list[Any],
) -> list[tuple[int, dict[str, Any]]]:
    """
    Build the (index, slot-like-dict) items the per-slot mapping loop
    iterates over. When the editor asset plan has active AI_VISUAL clips,
    those take priority (and are reshaped into the same slot-dict shape
    the loop expects); otherwise falls back to the raw visual plan's
    slots.
    """
    if editor_visual_clips:
        visual_items: list[tuple[int, dict[str, Any]]] = []
        for clip_index, clip in enumerate(
            editor_visual_clips,
            start=1,
        ):
            slot = {
                "slot_id": clip.get(
                    "slot_id",
                    clip.get(
                        "id",
                        "",
                    ),
                ),
                "label": clip.get(
                    "label",
                    f"Visual {clip_index}",
                ),
                "start": clip.get(
                    "start",
                    0.0,
                ),
                "end": clip.get(
                    "end",
                    clip.get(
                        "start",
                        0.0,
                    ),
                ),
                "asset_path": clip.get(
                    "asset_path",
                    clip.get(
                        "active_variant_path",
                        "",
                    ),
                ),
                "enabled": clip.get(
                    "active",
                    True,
                ),
                "state": "READY",
                "editor_clip_id": clip.get(
                    "id",
                    "",
                ),
                "display_mode": clip.get(
                    "display_mode",
                    "OVERLAY_CARD",
                ),
                "scale": clip.get(
                    "scale",
                    1.0,
                ),
                "position_x": clip.get(
                    "position_x",
                    0.0,
                ),
                "position_y": clip.get(
                    "position_y",
                    0.0,
                ),
                "source_type": clip.get(
                    "source_type",
                    "ai_generated",
                ),
            }
            visual_items.append(
                (
                    clip_index,
                    slot,
                )
            )
        return visual_items

    return list(
        enumerate(
            slots,
            start=1,
        )
    )


def resolve_mapped_asset(
    slot_index: int,
    slot: dict[str, Any],
    asset_map_by_id: dict[str, dict[str, Any]],
    asset_map_by_index: dict[int, dict[str, Any]],
    selection_start: float,
    keeps: list[Any],
    temporal_plan: dict[str, Any],
) -> dict[str, Any] | None:
    """
    Resolve one visual slot to its generated asset and map its source-
    video interval onto the final (post-cut, post-temporal-edit) tight
    timeline. Returns None whenever the slot should be skipped -- no
    matching/ready asset, the interval was entirely cut, or what remains
    is too short to be worth compositing.
    """
    if slot.get(
        "enabled",
        True,
    ) is False:
        return None

    slot_state = str(
        slot.get(
            "state",
            "",
        )
        or ""
    ).upper()

    if slot_state == "FAILED":
        return None

    slot_id = str(
        slot.get(
            "slot_id",
            "",
        )
        or ""
    )

    direct_asset_path = str(
        slot.get(
            "asset_path",
            "",
        )
        or ""
    )

    asset = None

    if direct_asset_path:
        direct_path = Path(
            direct_asset_path
        )
        if direct_path.exists():
            asset = {
                "path": str(
                    direct_path
                ),
                "state": "READY",
            }

    if asset is None:
        asset = (
            asset_map_by_id.get(
                slot_id
            )
            if slot_id
            else None
        )

    if asset is None:
        asset = asset_map_by_index.get(
            slot_index
        )

    if not asset:
        return None

    asset_state = str(
        asset.get(
            "state",
            "",
        )
        or ""
    ).upper()

    if asset_state == "FAILED":
        return None

    path = Path(
        str(
            asset.get(
                "path",
                "",
            )
        )
    )

    if not path.exists():
        return None

    try:
        source_start = float(
            slot.get(
                "start",
                0.0,
            )
        )
        source_end = float(
            slot.get(
                "end",
                source_start,
            )
        )
    except (
        TypeError,
        ValueError,
    ):
        return None

    mapped = map_source_interval_to_tight(
        source_start,
        source_end,
        selection_start,
        keeps,
    )

    if mapped is None:
        return None

    tight_start, tight_end = mapped
    tight_start, tight_end = map_tight_interval_to_final(
        tight_start,
        tight_end,
        temporal_plan,
    )

    if tight_end - tight_start < 0.5:
        return None

    return {
        "path": path,
        "tight_start": tight_start,
        "tight_end": tight_end,
        "label": slot.get(
            "label",
            f"Visual {slot_index}",
        ),
        "display_mode": normalize_display_mode(
            slot.get(
                "display_mode",
                "OVERLAY_CARD",
            )
        ),
        "scale": round(
            coerce_scale(
                slot.get(
                    "scale",
                    1.0,
                )
            ),
            2,
        ),
        "position_x": round(
            coerce_position(
                slot.get(
                    "position_x",
                    0.0,
                )
            ),
            3,
        ),
        "position_y": round(
            coerce_position(
                slot.get(
                    "position_y",
                    0.0,
                )
            ),
            3,
        ),
        "source_type": str(
            slot.get(
                "source_type",
                "ai_generated",
            )
            or "ai_generated"
        ),
    }


def write_mapped_plan(
    mapped_assets: list[dict[str, Any]],
    temporal_plan: dict[str, Any],
) -> None:
    """
    Write the resolved, tight-timeline-mapped visual plan to disk for
    diagnostics/debugging (the ffmpeg command itself is built straight
    from mapped_assets, not re-read from this file).
    """
    MAPPED_PLAN_PATH.write_text(
        json.dumps(
            {
                "version": 1,
                "source_plan": str(
                    PLAN_PATH
                ),
                "temporal_plan": str(
                    TEMPORAL_PLAN_PATH
                ),
                "temporal_applied": bool(
                    temporal_plan.get(
                        "applied",
                        False,
                    )
                ),
                "asset_count": len(
                    mapped_assets
                ),
                "assets": [
                    {
                        "path": str(
                            asset["path"]
                        ),
                        "start": round(
                            float(
                                asset["tight_start"]
                            ),
                            4,
                        ),
                        "end": round(
                            float(
                                asset["tight_end"]
                            ),
                            4,
                        ),
                        "label": asset.get(
                            "label",
                            "",
                        ),
                        "display_mode": asset.get(
                            "display_mode",
                            "OVERLAY_CARD",
                        ),
                        "scale": asset.get(
                            "scale",
                            1.0,
                        ),
                        "position_x": asset.get(
                            "position_x",
                            0.0,
                        ),
                        "position_y": asset.get(
                            "position_y",
                            0.0,
                        ),
                        "source_type": asset.get(
                            "source_type",
                            "ai_generated",
                        ),
                    }
                    for asset in mapped_assets
                ],
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )


def build_ffmpeg_command(
    mapped_assets: list[dict[str, Any]],
    render_settings: dict[str, Any],
) -> list[str]:
    """
    Build the ffmpeg command that overlays every mapped visual onto the
    tight video, one input per asset plus the content-rect-aware filter
    graph from build_filter().
    """
    command = [
        "ffmpeg",
        "-y",
        "-i",
        str(
            VIDEO_PATH
        ),
    ]

    for asset in mapped_assets:

        command.extend(
            [
                "-loop",
                "1",
                "-i",
                str(
                    asset["path"]
                ),
            ]
        )

    filter_complex = build_filter(
        mapped_assets,
        content_rect_from_settings(
            render_settings
        ),
    )

    command.extend(
        [
            "-filter_complex",
            filter_complex,
            "-map",
            "[outv]",
            "-map",
            "0:a?",
            "-c:v",
            "libx264",
            "-preset",
            "medium",
            "-crf",
            "20",
            "-c:a",
            "copy",
            "-movflags",
            "+faststart",
            "-shortest",
            str(
                TEMP_PATH
            ),
        ]
    )

    return command


def composite_and_replace_video(
    command: list[str],
) -> bool:
    """
    Run the ffmpeg compositing command and, on success, atomically
    replace the tight video with its composited output. On failure,
    cleans up the partial temp file and leaves the source footage
    untouched -- a failed visual composite should never abort the
    pipeline.
    """
    try:

        subprocess.run(
            command,
            cwd=ROOT,
            check=True,
        )

    except subprocess.CalledProcessError as exc:

        if TEMP_PATH.exists():

            try:
                TEMP_PATH.unlink()
            except OSError:
                pass

        print(
            (
                "WARNING: AI visual compositing failed with "
                f"exit code {exc.returncode}. "
                "Continuing with the source footage."
            ),
            flush=True,
        )

        return False

    os.replace(
        TEMP_PATH,
        VIDEO_PATH,
    )

    return True


def main() -> int:

    print(
        "ShortsFactory AI visual compositor starting...",
        flush=True,
    )

    if not VIDEO_PATH.exists():

        print(
            f"WARNING: Tight video does not exist: {VIDEO_PATH}",
            flush=True,
        )
        return 0

    if not PLAN_PATH.exists():

        print(
            "No AI visual plan exists; skipping visual compositing.",
            flush=True,
        )
        return 0

    if not MANIFEST_PATH.exists():

        print(
            "No generated AI visual assets exist; skipping visual compositing.",
            flush=True,
        )
        return 0

    plan = load_json(
        PLAN_PATH
    )

    manifest = load_json(
        MANIFEST_PATH
    )

    slots = plan.get(
        "slots",
        [],
    )

    assets = manifest.get(
        "assets",
        [],
    )

    if (
        not isinstance(
            slots,
            list,
        )
        or not isinstance(
            assets,
            list,
        )
        or not slots
        or not assets
    ):

        print(
            "Visual plan/assets are empty; skipping.",
            flush=True,
        )
        return 0

    selection_start = float(
        plan.get(
            "selection_start",
            0.0,
        )
        or 0.0
    )

    combined_plan = load_json(
        COMBINED_PLAN_PATH
    )
    temporal_plan = load_json(
        TEMPORAL_PLAN_PATH
    )

    keeps = compute_keeps(
        combined_plan
    )

    asset_map_by_index, asset_map_by_id = build_asset_maps(
        assets
    )

    (
        editor_visual_clips,
        render_settings,
        selection_start,
        selection_end,
    ) = load_render_context()

    mapped_assets: list[
        dict[str, Any]
    ] = []

    visual_items = build_visual_items(
        editor_visual_clips,
        slots,
    )

    for slot_index, slot in visual_items:

        if not isinstance(
            slot,
            dict,
        ):
            continue

        mapped_asset = resolve_mapped_asset(
            slot_index,
            slot,
            asset_map_by_id,
            asset_map_by_index,
            selection_start,
            keeps,
            temporal_plan,
        )

        if mapped_asset is not None:
            mapped_assets.append(
                mapped_asset
            )

    if not mapped_assets:

        print(
            "All planned visuals were removed by edits/cuts; skipping.",
            flush=True,
        )
        return 0

    write_mapped_plan(
        mapped_assets,
        temporal_plan,
    )

    command = build_ffmpeg_command(
        mapped_assets,
        render_settings,
    )

    print(
        f"Compositing AI visuals: {len(mapped_assets)}",
        flush=True,
    )

    for index, asset in enumerate(
        mapped_assets,
        start=1,
    ):

        print(
            (
                f"Visual {index}: "
                f"{asset['tight_start']:.2f}s -> "
                f"{asset['tight_end']:.2f}s  //  "
                f"{asset['label']}"
            ),
            flush=True,
        )

    if not composite_and_replace_video(
        command
    ):
        return 0

    print(
        "AI visual cutaways composited into tight video.",
        flush=True,
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
